name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_frog: ^0.1.0
  drift: ^2.1.0
  json_serializable: ^6.3.1
  sqflite: ^2.0.3+1
  todo:
    path: packages/todo

dev_dependencies:
  build_runner: ^2.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
